### ISSUE TITLE
Tailscale now at 1.56.0 

### ISSUE THREAD

**Issue by Node815** [hassio-addons/addon-tailscale#304] opened 2023-12-15 16:04 UTC
# Problem/Motivation

![image](https://github.com/hassio-addons/addon-tailscale/assets/20736534/f100a4b6-cf4c-4fad-9ba1-6c5862aa3358)

## Expected behavior

Updates should be applied

## Actual behavior

We are currently sitting on a stale update

## Steps to reproduce

Install Tailscale addon and see what your addon shows in the Tailscale Admin dashboard

## Proposed changes

Update this plugin more often or allow the ability to run the update from within the container either via the GUI or another means. 

Their update cadence seems pretty steady and already we are several versions behind. This version seems to add more functionality. 

https://tailscale.com/changelog#client

**Updated to now say Tailscale is at 1.56.1**

**Comment by lmagyar** [comment] 2023-12-16 09:48
See PR #305, it is merged, but not released, because v1.52.0 made some breaking changes to the cli, see #287, but those PRs addressing this are not merged yet.

**Comment by BrianGGG** [comment] 2024-01-06 15:22
Inquiring on the status of this?  Tailscale version is still 1.50

**Comment by frenck** [comment] 2024-01-07 13:30
Latest version is on dev.

Closing this issue, as it is a request for a release and not a bug report.

../Frenck

**Closed by frenck** 2024-01-07 13:30 UTC
