### ISSUE TITLE
Read-only Tailscale web UI

### ISSUE THREAD

**Issue by lmagyar** [hassio-addons/addon-tailscale#314] opened 2024-01-09 10:23 UTC
I see 3 related issues, but I don't know the solution. I think this should be better fixed with a workaround for HA in `tailscale web` code, that can eliminate the below mentioned http request and solve all issues. But I'm a total newbie in case of web development, so maybe somebody knows better.

## 1. How TS identifies the browser/user

As I see, some script running in the browser (when you press the "Viewing" button) tries to directly access `http://<device's TS IP>:5252/ok`, and when the browser is not part of the tailnet, certainly it fails. I see some workaround in the `tailscale web` source for synology and qnap to accept their user authentication.

So without a TS workaround for HA, I see 0 chance to access the non-read-only UI if the browser is not part of the tailnet but the user is an admin HA user.

## 2. Non-read-only UI opens up in a new tab/window

When I access HA's plain ***http*** UI (browser -> HA/Ingress (http) -> add-on's nginx -> tailscale web), this `http://<device's TS IP>:5252/ok` request is working if the browser is part of the tailnet.

But after login/authentication (to see the non-read-only UI of TS web), it opens up a *new page* with `http://<device's TS IP>:5252/?check=now`

I can't see how it can work with HA's UI.

## 3. Mixed content problem

When I access HA's ***httpS*** UI (browser -> **nginx add-on (https)** -> HA/Ingress (http) -> add-on's nginx -> tailscale web), this `http://<device's TS IP>:5252/ok` request is blocked with "(blocked:mixed-content)". As I understand the browser (Chrome) blocks the http request from a https page.

I have zero clue how to fix this. But this seems to be the side-effect of TS's home-made security/authentication code.

**Comment by willnorris** [comment] 2024-01-11 21:45
Hey @lmagyar, I work on the team that built new Tailscale web UI and can help provide some context.

Because the new web UI that launched in 1.56 has far more capabilities than the old web UI, we added some additional security safeguards, which is part of what you're running to.  As you've noted, the web UI runs in a read-only mode and a read-write mode.  The read-write mode is only accessible over the device's Tailscale IP address on port 5252, which allows us to use Tailscale itself to authenticate remote users and enforce access controls.  That does require that the device you're connecting *from* must have Tailscale installed and be on the same tailnet.  It also means that you can use your Tailscale ACLs to control which users on your tailnet can use the web UI remotely for different sets of devices.

As to the specific issues you're hitting:

1. The web UI is only served in read-write mode when accessed over the Tailcale IP.  The authentication code you see for synology and qnap is not working around that, instead it's hooking into those platform's auth model so that even the read-only mode is only accessible to admin users on those platform.  This was carried over from the old web UI and arguably could possibly be dropped since it is read-only, but we opted to keep it in place.  This was necessary on those platforms because of how they implement web UIs for plugins through CGI mode.  With how Home Assistant runs addons behind a reverse proxy, we didn't need to do anything special.  Home Assistant automatically enforces that only authorized users are able to access the Tailscale add-on.

2. This is working as designed.  The read-write client doesn't allow itself to be loaded in an iframe, so the login button will open a new tab if it detects it is currently framed (as is the case for Home Assistant).

3. The mixed content problem is a legit bug that we missed in our testing.  The `/ok` request is a connectivity check to see if you are even able to connect to the read-write client, and to display an error message if you want.  That client is always served over http, so will result in these mixed-content issues if the read-only client is served over https (this is a problem for all platforms, not just Home Assistant).  We'll probably just skip the connectivity check if the read-only client is being served over https, and add some help text that if you're aren't able to login then make sure you are connected to Tailscale.  We should have that included in the next release.

**Comment by lmagyar** [comment] 2024-01-12 16:27
Hey @willnorris, thank you for your detailed response and quick fix!

Now I'm thinking about the dual UI problem:
- The add-on config and the read-write tailscale web settings currently can conflict on the below parameters:
  - advertise-exit-node
  - advertise-routes
  - login-server
- Currently the add-on sets these parameters on (re)start based on the add-on configuration (basically a JSON/YAML file), but users can change these parameters through the read-write tailscale web later on. After the add-on restarts (maybe after a random power outage), it will overwrite any modification at a random moment.
- Though we can't blindly remove this 3 add-on config parameters, because the read-write tailscale web UI is not as accessible as the HA UI (we need a browser in the tailnet). So it is quite bad to say, that users can edit 10 parameters through the add-on config UI, but to edit the above mentioned 3, their browser must be in the tailnet. If they have access only through funnel, it will not work.

I don't know the solution, just writing about it.

Isn't it possible to add some `trusted_proxies` like parameter to tailscale web, and automatically enable the read-write UI, and even in an iframe, if the traffic comes through an "authenticated" connection (like: only a HA admin user can access this reverse-proxy "chain"). Just an idea, I'm a newbie in case of (web) development.

**Comment by willnorris** [comment] 2024-01-12 19:55
I agree... having multiple ways of setting some of these options, each working from a different source of truth, is guaranteed to cause conflicts with no perfect solution.  And nothing about that is really specific to Home Assistant, though I don't know how many other platforms have a similar declarative model for configuring Tailscale.  Kubernetes I suspect, and maybe infrastructure automation platforms like Terraform?

Since the different ways of configuring Tailscale are somewhat mutually exclusive, what about making it a user option?  Maybe addon-tailscale adds a YAML option of `manage-web-ui: bool`.  When set, all of the other yaml config is ignored and the user manages Tailscale exclusively through the web ui.  If false, then we can add a way to lock the web UI into read-only mode, so then it's still useful for getting Tailscale initially logged in and for quickly viewing settings, but actual configuration is done through YAML.  Or maybe you don't even need an explicit option... If the config is empty, you assume the user is going to use the web UI, but if they specify any YAML config, then we put the web UI into read-only mode.

**Comment by lmagyar** [comment] 2024-01-13 12:49
Perfect. :) I think a _locked read-only web UI_ is the perfect solution currently. (Note: I'm not the original developer of this add-on, just made some PRs into it.)

---

Later, when the below options (or most of them) has read-write web UI, we can drop the add-on options and go 100% web UI:

- already part of web UI
  - advertise_exit_node
  - advertise_routes
    - _though the add-on adds the local subnets on startup, so a web-UI-only manual config can be seen a bit as a regression_
  - login_server

- add-on options that hopefully won't make the add-on un-start-able (and loosing the web UI also)
  - accept_dns
  - snat_subnet_routes
  - tags
  - funnel
  - proxy
  - proxy_and_funnel_port
    - _the current add-on configuration doesn't use the full capabilities of tailscale serve, so a web UI would be really great_
  - accept_routes
    - _can definitely soft-brick the whole HA device, not just the add-on, there is protection inside the add-on against this (manipulating routing tables)_

- options that can't be part of read-write web UI:
  - userspace_networking
    - _this is a tailscaled option_
    - _this can disable/enable the current MSS clamping (for site-to-site networking) and routing protection logic (see the comment on accept_routes above) inside the add-on_
  - taildrop
    - _this starts up a longrun internal add-on service to accept incoming files (`tailscale file get --loop ...`), maybe a permanent tailscale service like `tailscale serve --bg ...` can eliminate the need for it_

**Comment by lmagyar** [comment] 2024-01-25 08:21
Tested v1.58.2, the "https fix" works as expected. Thank you.

Are there any planned schedule when will be the "locked read-only web UI" option available?

**Comment by willnorris** [comment] 2024-02-08 18:48
Okay, we just merged the new `-readonly` flag for `tailscale web`.  It will be in the 1.60 release, which is currently scheduled for next week.

**Comment by kdpuvvadi** [comment] 2024-02-16 12:47
For me i can't access read-write UI, getting connection refused option on accessing `<device>.homeassistant.tailnet-id.ts.net:5252`. Seems like port is not open. tried restarting both add-on and core but no awail.

**Comment by lmagyar** [comment] 2024-02-16 20:00
Yes, this read-only is intentional after 1.60. If you change anything on the webui, that will be lost after the add-on restarted, please use the add-on's config options.
I think we should add some note about this in the documentation. A PR will follow.

**Comment by lmagyar** [comment] 2024-02-16 20:09
Oh, sorry, 1.60 is not released in the add-on yet.

With add-on 0.15.0 (tailscale 1.58) you can access the read-write webui, but your browser's machine has to be part of the tailnet. There is no workaround. And you will lose any changes you made on the webui after the add-on is restarted.

The soon to be released new add-on version will not offer this ...5252 connection, will be read-only.

**Closed** 2024-02-17 21:37 UTC
