### ISSUE TITLE
Iptables?

### ISSUE THREAD

**Issue by LEJOUI** [hassio-addons/addon-tailscale#14] opened 2021-08-20 19:05 UTC
# Problem/Motivation
When starting the add-on it fails on my internal LAN. Acces to the internet is not possible, only accessing the Tailscale LAN. Stopping the add-on brings it all back. Logs seems to issue a problem with iptables. 

## Expected behavior

Have also acces to the big scary internet

## Actual behavior

```
2021/08/20 20:49:53 router: failed to delete legacy rule, continuing anyway: checking for [-m comment --comment tailscale -i tailscale0 -j ACCEPT] in filter/FORWARD: running [/sbin/iptables -t filter -C FORWARD -m comment --comment tailscale -i tailscale0 -j ACCEPT --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load match `comment':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.
2021/08/20 20:49:53 router: failed to delete legacy rule, continuing anyway: checking for [-m comment --comment tailscale -o eth0 -j MASQUERADE] in nat/POSTROUTING: running [/sbin/iptables -t nat -C POSTROUTING -m comment --comment tailscale -o eth0 -j MASQUERADE --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load match `comment':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.
```

## Steps to reproduce
Home Assistant OS in a VM with proxmox

## Proposed changes

**Comment by frenck** [comment] 2021-08-21 09:52
duplicate of #12

**Closed by frenck** 2021-08-21 09:52 UTC
