### ISSUE TITLE
Provide option to disable advertising subnets

### ISSUE THREAD

**Issue by michaelyork** [hassio-addons/addon-tailscale#203] opened 2023-05-16 08:32 UTC
# Problem/Motivation

Some may prefer to not advertise subnets from their HA instance.

## Proposed changes

Provide a config option to not advertise subnet routes.

**Comment by frenck** [comment] 2023-05-16 08:55
Closing this issue, as it is not a bug report/issue, but an feature request.

../Frenck

**Closed by frenck** 2023-05-16 08:55 UTC
