### ISSUE TITLE
Please turn funnel off by default and consider turning proxy off by default

### ISSUE THREAD

**Issue by gebrk** [hassio-addons/addon-tailscale#272] opened 2023-10-16 21:10 UTC
While the funnel setting has no effect with funnel turned off on a tailnet level, I feel that an option which has the potential to expose a home-assistant installation to the entire internet should be opt-in. I found it rather an unpleasant surprise seeing that this was enabled by default as I saw this addon as a way to get **secure** remote access.
While proxy mode is a nice addition which will allow me to remove the separate nginx reverse proxy addon, having proxy enabled on this addon by default broke my existing remote access setup as it grabbed port 443 before I added the correct trusted proxies line. It was easy enough to fix having local access, but not the smoothest experience. 

Thanks for building this addon.

**Comment by Megastrik3** [comment] 2023-10-16 22:16
I too have had an issue with turning funneling off on my instance. I found that if I uninstall and reinstall the add-on funneling seems to stay off, however, if I try to manually turn funneling on, it can't be turned off. Thank you for adding the feature though! It will prove very useful in the future!

**Comment by codyc1515** [comment] 2023-10-17 00:27
Majority of users using Tailscale add-on would want a straightforward and easy way to get HA set-up. It makes sense then that it is enabled by default.

Note that while this add-on does connect to Tailscale that this does not actually expose the instance to the internet directly as the user must still amend the ACL in Tailscale itself in order to enable Funnel.

**Comment by frenck** [comment] 2023-10-17 05:13
> While the funnel setting has no effect with funnel turned off on a tailnet level, I feel that an option which has the potential to expose a home-assistant installation to the entire internet should be opt-in.

Could not agree more! 👍
Will make an adjustment,

> Majority of users using Tailscale add-on would want a straightforward and easy way to get HA set-up.

Interesting information. Where can I find the numbers this was based on?

../Frenck

**Comment by theFeverDog** [comment] 2023-10-17 06:11
> if I try to manually turn funneling on, it can't be turned off.

I can confirm this issue: after turning funnel on, it seems to stay activated even when setting funnel = false again (even after multiple restarts).

**Comment by anaisbetts** [comment] 2023-10-17 07:35
Please please please do not silently expose services to the public Internet without consent in an update - this is full-on **irresponsible**.

**Comment by frenck** [comment] 2023-10-17 07:36
> Please please please do not silently expose services to the public Internet without consent in an update - this is full-on irresponsible.

It doesn't.. it needs to be explicitly enabled on the Tailscale end still. Don't worry.

**Comment by frenck** [comment] 2023-10-17 07:37
> > if I try to manually turn funneling on, it can't be turned off.
> 
> I can confirm this issue: after turning funnel on, it seems to stay activated even when setting funnel = false again (even after multiple restarts).

Hmmm ok that might be a bug. Thanks for reporting / testing that 👍

**Comment by anaisbetts** [comment] 2023-10-17 07:39
> It doesn't.. it needs to be explicitly enabled on the Tailscale end still

This tooltip states the opposite, though this may be a bug in Tailscale's UI because it seems to contradict their documentation about Tailscale Funnel requiring ACL entries

![image](https://github.com/hassio-addons/addon-tailscale/assets/1396/d9640c2b-dea9-48c7-b14c-e3269f7c6c2f)

**Comment by frenck** [comment] 2023-10-17 07:40
@anaisbetts Assume you've test it... what did you find out? Is it open to the internet?

**Comment by anaisbetts** [comment] 2023-10-17 07:42
@frenck That's unclear - both with Tailscale connected and disconnected, `https://homeassistant.[MY TAILNET]` reports 400 Bad Request. _Some_ HTTPS server is answering the request though which still makes me nervous

**Comment by frenck** [comment] 2023-10-17 07:44
> Some HTTPS server is answering the request though which still makes me nervous

That's not good, nor is that the intention. This can either mean the ACL isn't correct / the default anymore; or something else changed. I haven't noticed the behavior on my end when testing this out.

Anyways, as per above mentioned already. I agree on the sentiment and will adjust the add-on to disable by default. (Although, as per above, there might be a bug with that).

**Comment by anaisbetts** [comment] 2023-10-17 07:45
Thanks for looking into this quickly @frenck

**Comment by theFeverDog** [comment] 2023-10-17 07:58
In my testing, I saw that if the ACL does not allow funnel (as per default), the addon logs a notice „Tailscale‘s Funbel support is disabled […]“. However, the next line in the log then states that Funnel started successfully. 

Looking at the code, this might be because the code exits with an OK insteqd with a NOK. However the actual command that turns funnel on only comes after the code already exited. So as long as the ACL forbids it, it does not seem to start a funnel.

**Comment by anaisbetts** [comment] 2023-10-17 08:36
This is likely because Tailscale Funnel released this snippet as part of their documentation and encouraged people to use it (which I did):

```json
		{
			// Funnel policy, which lets tailnet members control Funnel
			// for their own devices.
			// Learn more at https://tailscale.com/kb/1223/tailscale-funnel/
			"target": ["autogroup:members"],
			"attr":   ["funnel"],
		},
```

**Comment by theFeverDog** [comment] 2023-10-17 08:55
> > > if I try to manually turn funneling on, it can't be turned off.
> > 
> > 
> > I can confirm this issue: after turning funnel on, it seems to stay activated even when setting funnel = false again (even after multiple restarts).
> 
> Hmmm ok that might be a bug. Thanks for reporting / testing that 👍

The same bug seems to happen for proxy as well: I just disabled proxy by setting it to false, restarted the addon, but can happily continue browsing over HTTPS.

Both proxy and funnel depend on „tailscale serve“, so this might explain why funnel also seems to continue running even when disabled.

I‘ll try to open a new issue this evening.

**Comment by frenck** [comment] 2023-10-17 08:56
Thanks, @theFeverDog No specific issue needed, this one is fine to track it.

As said, will take a look as soon as I am able too.

../Frenck

**Comment by lmagyar** [comment] 2023-10-17 14:23
I'm the author of this functionality:

1. This is opt in. The add-on tries to start the funnel service inside itself, **if it is already enabled on the tailscale admin console**. If somebody already enabled it, yes, it will "magically" publish it on the internet. But this is the configuration on the admin console, it just had no effect until this got implemented in the add-on.

2. After turning it off, it still enabled: Tailscale seems to got memory, even if we do not start `tailscale serve` or `tailscale funnel` it remains active. This wasn't this way in tha past, more than 100 user tested this proxy and funnel functionality before it got relesed here, and nobody noticed. :( I will make a PR soon.

**Comment by frenck** [comment] 2023-10-17 14:25
> This is opt in

That was pointed out above, still agree with the sentiment, going to disable it by default.

**Comment by anaisbetts** [comment] 2023-10-17 17:40
>  The add-on tries to start the funnel service inside itself, if it is already enabled on the tailscale admin console. If somebody already enabled it, yes, it will "magically" publish it on the internet.

I don't think that the logic of "If they ever wanted to publish _any_ service, they probably want to publish _this service too_" is reasonable here. In fact, despite the feature being enabled, I don't have *any* service published / funneled at the moment! But because I had the ability to do so set up, my HA instance was exposed to the public Internet

**Comment by frenck** [comment] 2023-10-17 17:41
Let's stop this discussion. The message has been clear, the issue is clear, the decision is made. No need to continue further. It doesn't add to resolving the issue at hand.

../Frenck

**Comment by lmagyar** [comment] 2023-10-17 20:12
Just a note: PR #273 is ready to review (by default disabled proxy and funnel functionality, and fixed disabled behavior for both).

**Comment by gebrk** [comment] 2023-10-18 18:10
I'm not suggesting duplicating documentation tailscale provide but briefly documenting how their documented features might be applied to the home-assistant addon. I would not expect them to document this so I'm not going to suggest it to them. I know the features exist and how to use them, I thought others might find some pointers useful.

**Comment by frenck** [comment] 2023-10-18 18:12
> I'm not suggesting duplicating documentation tailscale provide but briefly documenting how their documented features might be applied to the home-assistant addon.

Basically, 90% of their documentation applies... Let's not go down that path.

**Comment by gebrk** [comment] 2023-10-18 18:20
You probably want to remove this section then: https://github.com/hassio-addons/addon-tailscale/blob/16408503bb0e2f116d8207fc2dde98ce7fdbdd65/tailscale/DOCS.md?plain=1#L156-L165 since it duplicated tailscale documentation and without explaining the implications of the acl.

**Comment by frenck** [comment] 2023-10-18 18:55
Agreed 👍

**Comment by lmagyar** [comment] 2023-10-18 20:40
OK, modified the funnel docs also in the PR: ea5a2b2992c0130abac657012250397654d36b0f

**Comment by anaisbetts** [comment] 2023-10-19 10:21
>It might be worth adding a recommendation to acl tag the home-assistant device in the documentation.

I think this has consequences that reach a bit farther, tagged machines lose their "ownership" so the rules don't match the same way as machines added directly

**Closed** 2023-10-22 16:26 UTC
